name: Deploy

on: [push]

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - name: Install dependencies
      run: npm install
    - name: Building the project
      run: npm run build
  
  deploy_to_heroku:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "gruff-website"
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
