name: Deploy Gruff

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm install
        npm run build --if-present
      env:
        API_URL: ${{ secrets.API_URL }}
        ASSETS_BUCKET: ${{ secrets.ASSETS_BUCKET }}
        ASSETS_BUCKET_NAME: ${{ secrets.ASSETS_BUCKET_NAME }}
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}  
        SECRET_KEY: ${{ secrets.SECRET_KEY }} 
    - name: Deploy to Heroku  
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: "gruff-website"
      if: job.status == 'success'
      run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master

